############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2


[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "Services"
url = "service/"
#hasChildren = true


[[main]]
name = "Contact"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2


[[footer]]
name = "Services"
url = "service/"
weight = 4

[[footer]]
name = "Contact"
url = "contact/"
weight = 7